debug: true

database:
  driver: pdo_mysql
  dbname: iis-import
  user: ***
  password: ***
  host: 127.0.0.1

import_folder: /vagrant/import

amqp:
  host: udb3.dev
  port: 5672
  user: vagrant
  password: ***
  vhost: udb3-vagrant
  consumer_tag: udb3-vagrant
  publish:
    exchange: udb2.vagrant.x.entry
  message:
    base_url: http://iis-udb.dev/events
    author: importsUDB3

aws:
  credentials:
    key: ***
    secret: ***
  region: ***
  version: ***
  bucket: ***

category:
  taxonomy_namespace: http://www.cultuurdatabank.com/XMLSchema/CdbXSD/3.2/FINAL
  flanders_region: http://taxonomy.uitdatabank.be/api/domain/flandersregion/classification