debug: true

database:
  driver: pdo_mysql
  dbname: ***
  user: ***
  password: ***
  host: 127.0.0.1

bootstrap: []

input_folder: ***

amqp:
  host: example.com
  port: 5672
  user: foo
  password: bar
  vhost: example
  publish:
    exchange: udb2.e.prod

base_url_output: output.uitdatabank.be
