<?php
/**
 * Created by PhpStorm.
 * User: jonas
 * Date: 13.09.16
 * Time: 14:28
 */

namespace CultuurNet\UDB3\IISImporter;

use CultuurNet\UDB3\XmlString;

interface StoreProviderInterface
{
    /**
     * @param XmlString $xmlString
     *  The XmlString of the Event
     * @param string $cdbid
     *   The internal ID, generated by the importer itself.
     * @param string $externalId
     *   The external ID, that the partner gives
     * @return boolean
     */
    public function writeEvent($xmlString, $cdbid, $externalId);
}
