<?php
/**
 * @file
 */

namespace CultuurNet\UDB3\IISImporter\Console;

use Lurker\Event\FilesystemEvent;
use Lurker\ResourceWatcher;
use Knp\Command\Command;

class WatchCommand extends Command {

    protected  function execute(InputInterface $input, OutputInterface $output)
    {
        $app = $this->getSilexApplication();

        $watcher = new ResourceWatcher;
        $watcher->track('import_files', $app['config']['input_folder']);

        $watcher->addListener('import_files', function (FilesystemEvent $event) {
            echo $event->getResource() . 'was' . $event->getTypeString();
        });

        $watcher->start();

        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }

}
